[package]
name = "flood-rs"
version = "0.0.12"
edition = "2021"
license = "MIT"
description = "Bit and octet streams"
repository = "https://github.com/piot/flood-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
